cas-scheduler:
  lectures:
    extract: true
    pdf:
      filename:
        technik: "M_T_Lehrveranstaltungen.pdf"
        wirtschaft: "M_W_Lehrveranstaltungen.pdf"
      date-pattern: "dd.MM.yyyy"
    json:
      output:
        filename: "lectures/json/lectures.json"
    ics:
      uid: "cas-scheduler"
      prod-id: "-//CAS Scheduler//iCal4j 2.0//EN"
      output: "lectures/ics/"
  modules:
    extract: true
    pdf:
      filename:
        technik: "M_T_Modulhandbuch.pdf"
        wirtschaft: "M_W_Modulhandbuch.pdf"
      date-pattern: "dd.MM.yyyy"
    json:
      output:
        filename: "modules/json/modules.json"
  lecture-modules:
      json:
        output: "lecture-modules/json/lecture-modules.json"